In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Read the csv file

In [4]:
df=pd.read_csv("Amazon_data.csv")
df.head()

,Smartphone,Rating,Reviews count,Offer price,Actual price,Saving,Delivery,Status of stock & more offers
0,"Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage) | 2....",4.2 out of 5 stars,"87,809","₹9,499","₹10,999","Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN
1,"Redmi 9A (Nature Green, 2GB RAM, 32GB Storage)...",4.2 out of 5 stars,"74,587","₹6,999","₹8,499","Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
2,Redmi 9A (Sea Blue 2GB RAM 32GB Storage) | 2GH...,4.2 out of 5 stars,"74,587","₹6,999","₹8,499","Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
3,"Redmi Note 10 (Aqua Green, 4GB RAM, 64GB Stora...",4.2 out of 5 stars,"95,519","₹13,999","₹15,999","Save ₹2,000 (13%)",FREE Delivery by Amazon,NaN
4,"Redmi 9 (Carbon Black, 4GB RAM, 64GB Storage) ...",4.2 out of 5 stars,"87,809","₹9,499","₹10,999","Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN

In [3]:
df.shape

(1367, 8)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1367 entries, 0 to 1366
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Smartphone                     1367 non-null   object
 1   Rating                         1367 non-null   object
 2   Reviews count                  1367 non-null   object
 3   Offer price                    1153 non-null   object
 4   Actual price                   1041 non-null   object
 5   Saving                         1150 non-null   object
 6   Delivery                       1367 non-null   object
 7   Status of stock & more offers  498 non-null    object
dtypes: object(8)
memory usage: 85.6+ KB

In [5]:
len(df[df.duplicated()])

56

In [6]:
df[df.duplicated()]

,Smartphone,Rating,Reviews count,Offer price,Actual price,Saving,Delivery,Status of stock & more offers
144,Nokia 3310 Dual SIM Feature Phone with MP3 Pla...,4.2 out of 5 stars,"12,691","₹4,006","₹4,399",Save ₹393 (9%),FREE Delivery by Amazon,More Buying Choices
145,"Samsung Metro 313 (SM-B313E, Grey)",4.1 out of 5 stars,"7,398","₹2,340",NaN,Get it by,Paid,NaN
192,Nokia 3310 Dual SIM Feature Phone with MP3 Pla...,4.2 out of 5 stars,"12,691","₹4,290","₹4,399",Save ₹109 (2%),FREE Delivery by Amazon,NaN
312,"Samsung Galaxy A72 (Black, 8GB RAM, 128GB Stor...",4.2 out of 5 stars,466,"₹34,999","₹41,999","Save ₹7,000 (17%)",FREE Delivery by Amazon,NaN
336,New Apple iPhone 12 Pro (256GB) - Pacific Blue,4.6 out of 5 stars,576,"₹1,18,900","₹1,29,900","Save ₹11,000 (8%)",FREE Delivery by Amazon,NaN
416,"Mi Redmi 8 Smartphone (Onyx Black, 4GB RAM, 64...",4.1 out of 5 stars,"1,070","₹10,850","₹12,999","Save ₹2,149 (17%)",Paid,Only 2 left in stock.
417,"Honor 7A (Blue, 3GB RAM, 32GB Storage)",4.7 out of 5 stars,3,"₹8,999","₹10,999","Save ₹2,000 (18%)",FREE Delivery by Amazon,NaN
438,"Kechaoda K55+ (Silver, 32GB)",4.1 out of 5 stars,109,₹999,"₹1,299",Save ₹300 (23%),FREE Delivery by Amazon,More Buying Choices
441,"I KALL K48 Keypad Mobile (1.8 Inch, Big Batter...",4.4 out of 5 stars,5,₹719,₹999,Save ₹280 (28%),Paid,NaN
442,"Vivo U20 (Racing Black, Snapdragon 675 AIE, 4G...",4.3 out of 5 stars,"22,750",NaN,NaN,NaN,Paid,NaN
456,"Redmi 9i (Nature Green, 4GB RAM, 128GB Storage)",4.1 out of 5 stars,"1,370",NaN,NaN,NaN,Paid,NaN
484,"Mi Max 2 (Black, 4GB RAM, 64GB Storage)",4.3 out of 5 stars,"5,014","₹16,999","₹17,999","Save ₹1,000 (6%)",FREE Delivery by Amazon,More Buying Choices
491,"(Renewed) Redmi Note 7 Pro (Nebula Red, 64GB, ...",4.0 out of 5 stars,28,"₹9,849","₹15,999","Save ₹6,150 (38%)",FREE Delivery by Amazon,Only 1 left in stock.
504,"MI Poco X3 (Cobalt Blue, 8GB RAM / 128 Storage)",4.2 out of 5 stars,269,"₹22,999",NaN,Get it by,Paid,NaN
529,"Redmi 6 (Black, 3GB RAM, 32GB Storage)",4.1 out of 5 stars,"14,007","₹8,999",NaN,Get it by,Paid,Only 1 left in stock.
530,"Vivo Y72 5G (Prism Magic, 8GB RAM, 128GB Stora...",4.0 out of 5 stars,153,"₹21,689","₹25,689","Save ₹4,000 (15%)",Paid,NaN
543,"Redmi Xiaomi Note 7 Pro Phone (Neptune Blue, 4...",4.2 out of 5 stars,752,"₹14,980","₹15,999","Save ₹1,019 (6%)",Paid,Only 1 left in stock.
546,Nillkin Super Frosted Hard PC Back Case Cover ...,4.4 out of 5 stars,40,₹499,₹990,Save ₹491 (50%),FREE Delivery by Amazon,More Buying Choices
552,"Note 7 Pro (Space Black, 64GB, 4GB RAM)",4.2 out of 5 stars,971,NaN,NaN,NaN,Paid,NaN
555,Lava Gem Wave Big Screen Dual SIM KEYPAD Mobile,4.2 out of 5 stars,18,"₹1,849","₹1,899",Save ₹50 (3%),Paid,NaN
581,"Mi A2 (Blue, 6GB RAM, 128GB Storage)",4.0 out of 5 stars,"45,901","₹19,990","₹20,500",Save ₹510 (2%),FREE Delivery by Amazon,Only 2 left in stock.
600,Nillkin Case for Samsung Galaxy S10 S 10 Lite ...,5.0 out of 5 stars,2,₹743,"₹1,499",Save ₹756 (50%),Paid,More Buying Choices
601,"Kechaoda A6 Tripple Sim 3.5"" Inch Large Screen...",5.0 out of 5 stars,1,"₹1,549","₹1,990",Save ₹441 (22%),Paid,NaN
602,"MI Poco X3 (Cobalt Blue, 6GB RAM / 64GB Storage)",4.2 out of 5 stars,269,NaN,NaN,NaN,Paid,NaN
603,"Vivo Y72 5G (Slate Gray, 8GB RAM, 128GB Storag...",4.0 out of 5 stars,153,"₹21,689","₹25,689","Save ₹4,000 (15%)",Paid,NaN
604,"TECNO Spark 7T(Magnet Black, 4GB RAM,64GB Stor...",4.0 out of 5 stars,"4,611","₹11,498","₹12,998","Save ₹1,500 (11%)",Paid,NaN
608,"Redmi Note 7 (Onyx Black, 4GB RAM, 64GB Storage)",4.3 out of 5 stars,561,"₹14,990",NaN,Get it by,Paid,Only 2 left in stock.
624,Nillkin Slim Frosted Anti-Falling Anti Fingerp...,5.0 out of 5 stars,6,₹525,"₹1,999","Save ₹1,474 (74%)",FREE Delivery by Amazon,NaN
631,"Samsung Galaxy A31 (Prism Crush Black, 6GB RAM...",4.2 out of 5 stars,"2,236",NaN,NaN,NaN,Paid,NaN
659,"Tecno Pova (4GB,64GB) (Speed Purple)",4.1 out of 5 stars,15,"₹11,576.25","₹11,999",Save ₹422.75 (4%),First Order Free Delivery,More Buying Choices
688,"(Renewed) Vivo Y91i (Ocean Blue, 2GB RAM, 32GB...",4.2 out of 5 stars,5,"₹6,999","₹8,490","Save ₹1,491 (17%)",Paid,Only 1 left in stock.
887,Vivo V5s (Matte Black),4.1 out of 5 stars,631,"₹16,990","₹20,990","Save ₹4,000 (19%)",Paid,Only 1 left in stock.
894,Quickshel M16 BIS Approved MP3 Playback Blueto...,4.0 out of 5 stars,1,"₹1,000","₹1,099",Save ₹99 (9%),FREE Delivery by Amazon,NaN
938,"Nillkin for Samsung Galaxy S21 Plus Case, CamS...",5.0 out of 5 stars,6,"₹1,049","₹2,999","Save ₹1,950 (65%)",Paid,NaN
946,New Apple iPhone 12 Pro (512GB) - Gold with Ap...,4.6 out of 5 stars,576,"₹1,44,800","₹1,54,800","Save ₹10,000 (6%)",Paid,NaN
949,"Vivo V20 (Sunset Melody, 8GB RAM, 256GB Storag...",4.3 out of 5 stars,"1,868",NaN,NaN,NaN,Paid,NaN
954,India Gadgets - Armor X7 Pro Rugged Android Mo...,4.4 out of 5 stars,3,"₹16,250","₹22,500","Save ₹6,250 (28%)",First Order Free Delivery,NaN
955,Kechaoda K-55 Plus Slim Mobile Phone with Came...,5.0 out of 5 stars,1,"₹1,099","₹1,399",Save ₹300 (21%),Paid,NaN
1009,New Apple iPhone 12 Pro (128GB) - Silver with ...,4.6 out of 5 stars,576,"₹1,13,300","₹1,21,800","Save ₹8,500 (6%)",Paid,NaN
1011,Mi Xiaomi MI Redmi Note 7S 4GB/64 GB Moonlight...,4.3 out of 5 stars,63,"₹13,499","₹13,999",Save ₹500 (4%),FREE Delivery by Amazon,Only 1 left in stock.
1023,Blackview India s - BV9900E Mobile Phone: 6Gb ...,5.0 out of 5 stars,1,"₹34,800","₹38,000","Save ₹3,200 (8%)",First Order Free Delivery,NaN
1033,IKALL K60 Gold Series Multimedia Feature Keypa...,4.6 out of 5 stars,3,"₹1,999","₹2,999","Save ₹1,000 (33%)",Paid,NaN
1039,Nillkin Case for Xiaomi Mi 11X 11 X / 11X Pro/...,4.0 out of 5 stars,1,"₹1,299","₹2,499","Save ₹1,200 (48%)",FREE Delivery by Amazon,Only 1 left in stock.
1103,"Vivo Y20G 2021 (Purist Blue, 4GB RAM, 64GB Sto...",4.1 out of 5 stars,139,NaN,NaN,NaN,Paid,NaN
1104,"Nillkin Screen Guard for Apple iPhone Xs (5.8""...",5.0 out of 5 stars,1,₹799,₹999,Save ₹200 (20%),FREE Delivery by Amazon,Only 1 left in stock.
1105,New Apple iPhone 12 (128GB) - White with Apple...,4.6 out of 5 stars,"4,260","₹83,850","₹89,800","Save ₹5,950 (6%)",Paid,NaN
1151,Nillkin Nature Series Transparent Silicone TPU...,4.0 out of 5 stars,2,₹750,"₹1,299",Save ₹549 (42%),Paid,Only 1 left in stock.
1152,Nillkin Case for LG V40 V 40 ThinQ Super Frost...,5.0 out of 5 stars,1,"₹1,289","₹1,499",Save ₹210 (14%),First Order Free Delivery,Only 1 left in stock.
1175,Nillkin Polycarbonate Compatible with Magnetic...,4.6 out of 5 stars,41,"₹3,999","₹5,999","Save ₹2,000 (33%)",First Order Free Delivery,NaN
1176,"(Renewed) OPPO Reno 2 (Ocean Blue, 8GB RAM, 25...",4.1 out of 5 stars,59,"₹24,999","₹39,999","Save ₹15,000 (38%)",FREE Delivery by Amazon,Only 1 left in stock.
1220,Nillkin Case for Xiaomi Mi 11X 11 X / 11X Pro/...,5.0 out of 5 stars,1,"₹1,699","₹1,799",Save ₹100 (6%),FREE Delivery by Amazon,Only 1 left in stock.
1223,Beetel M60 Corded Phone (Black),4.4 out of 5 stars,7,"₹1,477","₹1,590",Save ₹113 (7%),FREE Delivery by Amazon,More Buying Choices
1224,Nillkin Case for Xiaomi Mi 11X 11 X / 11X Pro/...,5.0 out of 5 stars,1,"₹1,699","₹1,799",Save ₹100 (6%),FREE Delivery by Amazon,Only 1 left in stock.
1225,"KECHAODA K50 Dual Sim, Black",5.0 out of 5 stars,1,"₹1,199",NaN,Get it,Paid,Only 1 left in stock.
1226,Nillkin Super Frosted Shield Pro Magnetic Hard...,5.0 out of 5 stars,2,"₹1,799","₹3,999","Save ₹2,200 (55%)",FREE Delivery by Amazon,Only 1 left in stock.
1280,"Nillkin Case for Apple iPhone 11 Pro Max (6.5""...",4.5 out of 5 stars,2,NaN,NaN,NaN,Paid,NaN

In [7]:
df['Smartphone'].unique()

array(['Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage) | 2.3GHz Mediatek Helio G35 Octa core Processor',
       'Redmi 9A (Nature Green, 2GB RAM, 32GB Storage) | 2GHz Octa-core Helio G25 Processor | 5000 mAh Battery',
       'Redmi 9A (Sea Blue 2GB RAM 32GB Storage) | 2GHz Octa-core Helio G25 Processor | 5000 mAh Battery',
       ...,
       'Nillkin Case for Samsung Galaxy F62 F 62 / Samsung Galaxy M62 M 62 (6.7" Inch) Super Frosted Hard Back Cover PC Red Color',
       'Nillkin Case for Xiaomi Redmi Note 10 / Note 10S (6.43" Inch) Super Frosted Hard Back Cover PC White Color',
       'Nillkin Case for Samsung Galaxy A72 A 72 (6.7" Inch) Qin Genuine Classic Leather Flip Folio + Card Slot Black Color'],
      dtype=object)

which is not have any duplicate unko check krne ke liye

In [8]:
df[df['Smartphone']=='Nokia 3310 Dual SIM Feature Phone with MP3 Player, Wireless FM Radio and Rear Camera, Dark Blue']

,Smartphone,Rating,Reviews count,Offer price,Actual price,Saving,Delivery,Status of stock & more offers
142,Nokia 3310 Dual SIM Feature Phone with MP3 Pla...,4.2 out of 5 stars,"12,691","₹4,006","₹4,399",Save ₹393 (9%),FREE Delivery by Amazon,More Buying Choices
144,Nokia 3310 Dual SIM Feature Phone with MP3 Pla...,4.2 out of 5 stars,"12,691","₹4,006","₹4,399",Save ₹393 (9%),FREE Delivery by Amazon,More Buying Choices

use for number of one data duplicate checking

# Remove the duplicates

In [9]:
df.drop_duplicates(keep='first',inplace=True)

after apply this code remove all duplicte data permanantaly of all data

In [10]:
df[df['Smartphone']=='Nokia 3310 Dual SIM Feature Phone with MP3 Player, Wireless FM Radio and Rear Camera, Dark Blue']

,Smartphone,Rating,Reviews count,Offer price,Actual price,Saving,Delivery,Status of stock & more offers
142,Nokia 3310 Dual SIM Feature Phone with MP3 Pla...,4.2 out of 5 stars,"12,691","₹4,006","₹4,399",Save ₹393 (9%),FREE Delivery by Amazon,More Buying Choices

phle ye 2time tha jo ab remove ho gya

In [11]:
len(df[df.duplicated()])

0

phle 56 duplictes the jo ab remove ho chuke hai.

# check the shape after removing duplicates

In [12]:
df.shape

(1311, 8)

after removing duplicate shape bhi change ho gya

### Checking info of the dataset

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1311 entries, 0 to 1366
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Smartphone                     1311 non-null   object
 1   Rating                         1311 non-null   object
 2   Reviews count                  1311 non-null   object
 3   Offer price                    1105 non-null   object
 4   Actual price                   998 non-null    object
 5   Saving                         1102 non-null   object
 6   Delivery                       1311 non-null   object
 7   Status of stock & more offers  473 non-null    object
dtypes: object(8)
memory usage: 92.2+ KB

# Missing values in each Column

In [14]:
df.isnull().sum()

Smartphone                         0
Rating                             0
Reviews count                      0
Offer price                      206
Actual price                     313
Saving                           209
Delivery                           0
Status of stock & more offers    838
dtype: int64

for checking miising data in all columns

# Parcentage of Missing values in each Column

In [15]:
(df.isnull().sum()/df.shape[0])*100

Smartphone                        0.000000
Rating                            0.000000
Reviews count                     0.000000
Offer price                      15.713196
Actual price                     23.874905
Saving                           15.942029
Delivery                          0.000000
Status of stock & more offers    63.920671
dtype: float64

jiss bhi column me 40% se jyada null value hote hai unko remove kr diya jata hai. 'Status of stock & more offers'  iss column me 40% se jyada null value hai iss liye isko remove kiya jayega.

# Removeing above 40% null value

In [10]:
df.drop(['Status of stock & more offers'],axis=1,inplace=True)

In [11]:
(df.isnull().sum()/df.shape[0])*100

Smartphone        0.000000
Rating            0.000000
Reviews count     0.000000
Offer price      15.654718
Actual price     23.847842
Saving           15.874177
Delivery          0.000000
dtype: float64

removed ho gya .

# Removing unwanted characters and changing the datatype

# work on Rating Column

In [16]:
df.head()

,Smartphone,Rating,Reviews count,Offer price,Actual price,Saving,Delivery,Status of stock & more offers
0,"Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage) | 2....",4.2 out of 5 stars,"87,809","₹9,499","₹10,999","Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN
1,"Redmi 9A (Nature Green, 2GB RAM, 32GB Storage)...",4.2 out of 5 stars,"74,587","₹6,999","₹8,499","Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
2,Redmi 9A (Sea Blue 2GB RAM 32GB Storage) | 2GH...,4.2 out of 5 stars,"74,587","₹6,999","₹8,499","Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
3,"Redmi Note 10 (Aqua Green, 4GB RAM, 64GB Stora...",4.2 out of 5 stars,"95,519","₹13,999","₹15,999","Save ₹2,000 (13%)",FREE Delivery by Amazon,NaN
4,"Redmi 9 (Carbon Black, 4GB RAM, 64GB Storage) ...",4.2 out of 5 stars,"87,809","₹9,499","₹10,999","Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN

In [17]:
df['Rating'].head()

0    4.2 out of 5 stars
1    4.2 out of 5 stars
2    4.2 out of 5 stars
3    4.2 out of 5 stars
4    4.2 out of 5 stars
Name: Rating, dtype: object

In [18]:
df['Rating'].str.split(' ').head()

0    [4.2, out, of, 5, stars]
1    [4.2, out, of, 5, stars]
2    [4.2, out, of, 5, stars]
3    [4.2, out, of, 5, stars]
4    [4.2, out, of, 5, stars]
Name: Rating, dtype: object

use for changing in list data

In [19]:
df['Rating'].str.split(' ').str.get(0).head()

0    4.2
1    4.2
2    4.2
3    4.2
4    4.2
Name: Rating, dtype: object

In [20]:
df['Rating'].str.split(' ').str.get(0).astype(float).head()

0    4.2
1    4.2
2    4.2
3    4.2
4    4.2
Name: Rating, dtype: float64

for changing data type

In [21]:
df['Rating']= df['Rating'].str.split(' ').str.get(0).astype(float)

In [22]:
df.head()

,Smartphone,Rating,Reviews count,Offer price,Actual price,Saving,Delivery,Status of stock & more offers
0,"Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage) | 2....",4.2,"87,809","₹9,499","₹10,999","Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN
1,"Redmi 9A (Nature Green, 2GB RAM, 32GB Storage)...",4.2,"74,587","₹6,999","₹8,499","Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
2,Redmi 9A (Sea Blue 2GB RAM 32GB Storage) | 2GH...,4.2,"74,587","₹6,999","₹8,499","Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
3,"Redmi Note 10 (Aqua Green, 4GB RAM, 64GB Stora...",4.2,"95,519","₹13,999","₹15,999","Save ₹2,000 (13%)",FREE Delivery by Amazon,NaN
4,"Redmi 9 (Carbon Black, 4GB RAM, 64GB Storage) ...",4.2,"87,809","₹9,499","₹10,999","Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN

remove others in rating

In [23]:
df.dtypes

Smartphone                        object
Rating                           float64
Reviews count                     object
Offer price                       object
Actual price                      object
Saving                            object
Delivery                          object
Status of stock & more offers     object
dtype: object

# work on Review Count Column

In [24]:
df['Reviews count']=df['Reviews count'].str.replace(',','').astype(int)

apply for removeing comma in review column

In [25]:
df.head()

,Smartphone,Rating,Reviews count,Offer price,Actual price,Saving,Delivery,Status of stock & more offers
0,"Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage) | 2....",4.2,87809,"₹9,499","₹10,999","Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN
1,"Redmi 9A (Nature Green, 2GB RAM, 32GB Storage)...",4.2,74587,"₹6,999","₹8,499","Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
2,Redmi 9A (Sea Blue 2GB RAM 32GB Storage) | 2GH...,4.2,74587,"₹6,999","₹8,499","Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
3,"Redmi Note 10 (Aqua Green, 4GB RAM, 64GB Stora...",4.2,95519,"₹13,999","₹15,999","Save ₹2,000 (13%)",FREE Delivery by Amazon,NaN
4,"Redmi 9 (Carbon Black, 4GB RAM, 64GB Storage) ...",4.2,87809,"₹9,499","₹10,999","Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN

In [26]:
df.dtypes

Smartphone                        object
Rating                           float64
Reviews count                      int64
Offer price                       object
Actual price                      object
Saving                            object
Delivery                          object
Status of stock & more offers     object
dtype: object

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1311 entries, 0 to 1366
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Smartphone                     1311 non-null   object
 1   Rating                         1311 non-null   float64
 2   Reviews count                  1311 non-null   int64
 3   Offer price                    1105 non-null   object
 4   Actual price                   998 non-null    object
 5   Saving                         1102 non-null   object
 6   Delivery                       1311 non-null   object
 7   Status of stock & more offers  473 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 92.2+ KB

# Clean Offer Price Column

In [28]:
df.head()

,Smartphone,Rating,Reviews count,Offer price,Actual price,Saving,Delivery,Status of stock & more offers
0,"Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage) | 2....",4.2,87809,"₹9,499","₹10,999","Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN
1,"Redmi 9A (Nature Green, 2GB RAM, 32GB Storage)...",4.2,74587,"₹6,999","₹8,499","Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
2,Redmi 9A (Sea Blue 2GB RAM 32GB Storage) | 2GH...,4.2,74587,"₹6,999","₹8,499","Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
3,"Redmi Note 10 (Aqua Green, 4GB RAM, 64GB Stora...",4.2,95519,"₹13,999","₹15,999","Save ₹2,000 (13%)",FREE Delivery by Amazon,NaN
4,"Redmi 9 (Carbon Black, 4GB RAM, 64GB Storage) ...",4.2,87809,"₹9,499","₹10,999","Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN

In [29]:
df.drop_duplicates(keep='first',inplace=True)

for removing duplicates

In [30]:
df['Offer price'].unique()

array(['₹9,499', '₹6,999', '₹13,999', '₹11,499', nan, '₹24,999',
       '₹10,499', '₹14,999', '₹16,999', '₹12,999', '₹17,999', '₹7,999',
       '₹1,299', '₹11,999', '₹29,999', '₹7,299', '₹13,499', '₹12,490',
       '₹22,999', '₹1,245', '₹16,499', '₹34,999', '₹19,999', '₹10,990',
       '₹20,990', '₹15,499', '₹1,249', '₹21,999', '₹17,990', '₹1,410',
       '₹27,999', '₹3,324', '₹39,999', '₹19,990', '₹987', '₹16,990',
       '₹10,999', '₹1,264', '₹43,999', '₹1,390', '₹23,999', '₹49,999',
       '₹1,662', '₹18,999', '₹31,990', '₹1,752', '₹1,859', '₹1,576',
       '₹2,841', '₹22,990', '₹954', '₹54,999', '₹9,999', '₹13,990',
       '₹69,999', '₹1,650', '₹15,990', '₹55,999', '₹2,340', '₹50,999',
       '₹4,006', '₹1,575', '₹24,990', '₹2,250', '₹56,900', '₹9,490',
       '₹38,999', '₹999', '₹1,131', '₹42,999', '₹3,019', '₹18,499',
       '₹33,990', '₹35,990', '₹1,029', '₹27,499', '₹51,999', '₹29,990',
       '₹6,936', '₹1,430', '₹4,290', '₹28,999', '₹2,983', '₹11,939',
       '₹39,990', '₹25,990', '₹64,999', '₹18,470', '₹59,999', '₹3,750',
       '₹3,891', '₹18,990', '₹24,995', '₹1,191', '₹12,990', '₹35,999',
       '₹1,25,900', '₹34,990', '₹1,06,900', '₹4,155', '₹26,999',
       '₹14,500', '₹44,799', '₹1,15,900', '₹1,179', '₹8,990', '₹9,699',
       '₹9,990', '₹21,900', '₹47,999', '₹14,693', '₹13,299', '₹78,950',
       '₹2,785', '₹43,990', '₹14,830', '₹19,499', '₹14,489', '₹38,745',
       '₹1,835', '₹949', '₹9,449', '₹15,000', '₹13,199', '₹8,903',
       '₹8,999', '₹49,990', '₹24,851', '₹21,648', '₹32,990', '₹4,037',
       '₹76,700', '₹69,900', '₹1,242', '₹21,990', '₹30,490', '₹46,499',
       '₹899', '₹1,149', '₹7,850', '₹7,946', '₹74,091.64', '₹23,490',
       '₹1,18,900', '₹4,040', '₹799', '₹45,479', '₹74,900', '₹29,945',
       '₹17,885', '₹11,490', '₹1,032', '₹12,999.90', '₹1,80,890',
       '₹1,11,900', '₹1,849', '₹1,180', '₹1,279', '₹1,799', '₹1,16,900',
       '₹1,09,900', '₹6,199', '₹7,799', '₹1,08,050', '₹8,398', '₹69,899',
       '₹14,818', '₹36,999', '₹30,999', '₹10,850', '₹603', '₹12,500',
       '₹68,999', '₹6,599', '₹719', '₹63,699', '₹1,08,700', '₹17,499',
       '₹74,299', '₹16,550', '₹1,990', '₹29,200', '₹18,900', '₹9,648',
       '₹1,939', '₹9,056', '₹71,700', '₹1,199', '₹890', '₹70,340',
       '₹2,099', '₹1,24,999', '₹32,999', '₹16,800', '₹16,490', '₹24,499',
       '₹9,849', '₹1,349', '₹1,61,700', '₹1,21,900', '₹73,750',
       '₹1,29,900', '₹78,800', '₹94,900', '₹1,46,890', '₹13,699',
       '₹1,39,900', '₹14,002', '₹15,999', '₹777', '₹75,990', '₹21,780',
       '₹980', '₹17,721', '₹1,31,700', '₹1,76,890', '₹1,050', '₹14,499',
       '₹53,999', '₹1,925', '₹4,186', '₹499', '₹974', '₹14,980',
       '₹21,410', '₹21,689', '₹10,909', '₹1,36,890', '₹9,948', '₹23,190',
       '₹959', '₹14,448', '₹749', '₹25,390', '₹60,030', '₹17,689',
       '₹19,839', '₹1,11,500', '₹9,898', '₹1,55,900', '₹46,999',
       '₹28,000', '₹22,500', '₹13,922', '₹1,339', '₹57,990', '₹1,25,600',
       '₹13,825', '₹1,07,550', '₹1,18,700', '₹13,831', '₹14,990',
       '₹13,409', '₹72,990', '₹743', '₹1,549', '₹11,576.25', '₹525',
       '₹11,498', '₹25,000', '₹21,895', '₹68,990', '₹1,499', '₹1,18,600',
       '₹80,750', '₹74,300', '₹42,790', '₹24,850', '₹1,248', '₹19,899',
       '₹40,900', '₹11,689', '₹17,389', '₹1,025', '₹1,749', '₹22,000',
       '₹65,390', '₹1,28,600', '₹1,23,950', '₹9,500', '₹12,989',
       '₹27,490', '₹18,800', '₹25,915', '₹699', '₹18,994', '₹31,695',
       '₹25,489', '₹1,164', '₹8,835', '₹71,250', '₹14,170', '₹14,689',
       '₹1,20,700', '₹1,020', '₹1,089', '₹34,800', '₹4,490', '₹60,149',
       '₹9,780', '₹1,640', '₹11,049', '₹1,000', '₹10,624', '₹1,37,890',
       '₹16,940', '₹13,220', '₹1,285', '₹1,41,790', '₹16,951', '₹1,079',
       '₹9,698', '₹18,689', '₹9,700', '₹10,500', '₹1,22,600', '₹24,200',
       '₹5,999', '₹1,57,700', '₹11,990', '₹1,31,699', '₹1,899',
       '₹1,13,700', '₹95,890', '₹1,049', '₹23,990', '₹20,900', '₹1,045',
       '₹1,879', '₹37,999', '₹25,249', '₹25,980', '₹25,999', '₹59,450',
       '₹15,500', '₹37,930', '₹25,689', '₹990', '₹85,650', '₹1,59,900',
       '₹13,498', '₹13,000', '₹1,17,700', '₹849', '₹13,799', '₹2,999',
       '₹10,399', '₹23,487', '₹10,000', '₹1,099', '₹90,890', '₹21,970',
       '₹1,795', '₹18,135', '₹1,999', '₹950', '₹20,906', '₹10,748',
       '₹22,800', '₹1,077', '₹795', '₹19,850', '₹13,900', '₹1,433',
       '₹3,999', '₹9,598', '₹1,16,600', '₹1,23,700', '₹1,60,890',
       '₹76,099', '₹19,900', '₹22,100', '₹26,500', '₹22,490', '₹850',
       '₹10,199', '₹1,147', '₹1,829', '₹1,745', '₹10,950', '₹12,499',
       '₹169', '₹11,340', '₹1,747', '₹21,980', '₹13,899', '₹20,500',
       '₹860', '₹1,14,800', '₹28,990', '₹1,18,200', '₹70,470', '₹1,613',
       '₹1,46,600', '₹83,850', '₹8,500', '₹33,999', '₹10,751', '₹39,000',
       '₹1,27,890', '₹10,890', '₹1,45,989', '₹24,690', '₹63,990',
       '₹11,900', '₹1,11,700', '₹17,490', '₹21,199', '₹37,489',
       '₹1,44,800', '₹1,599', '₹16,250', '₹4,599', '₹26,289', '₹10,189',
       '₹996', '₹16,529', '₹1,32,890', '₹27,790', '₹19,490', '₹1,292',
       '₹1,41,700', '₹888', '₹19,800', '₹1,32,490', '₹84,850', '₹55,000',
       '₹24,399', '₹1,800', '₹18,590', '₹1,42,890', '₹1,399', '₹16,449',
       '₹4,499', '₹1,435', '₹1,13,300', '₹2,599', '₹31,500', '₹99,940',
       '₹30,990', '₹995', '₹23,989', '₹575', '₹99,800', '₹4,980',
       '₹80,999', '₹37,990', '₹2,199', '₹739', '₹1,965', '₹1,27,500',
       '₹20,750', '₹1,36,600', '₹965', '₹80,199', '₹11,980', '₹750',
       '₹1,39,890', '₹21,000', '₹79,199', '₹1,23,800', '₹15,390',
       '₹1,699', '₹1,295', '₹13,389', '₹1,50,890', '₹1,269', '₹1,16,400',
       '₹450', '₹2,950', '₹2,100', '₹1,949', '₹10,168', '₹1,289', '₹299',
       '₹3,880', '₹3,499', '₹24,000', '₹50', '₹1,250', '₹1,290', '₹219',
       '₹1,30,890', '₹3,399', '₹3,950', '₹4,999', '₹449', '₹690',
       '₹1,477', '₹2,850', '₹62,990', '₹12,000', '₹59,990', '₹95,289',
       '₹2,499', '₹975', '₹2,799', '₹879', '₹471', '₹278', '₹32,500',
       '₹399', '₹96,700', '₹1,119', '₹3,250', '₹1,015', '₹585',
       '₹1,130.50', '₹710', '₹1,01,600', '₹10,451'], dtype=object)

In [31]:
df['Offer price']= df['Offer price'].str.replace('₹','')
df['Offer price']= df['Offer price'].str.replace(',','')

it remove special character

In [5]:
df['Offer price'].notnull().sum()

1153

for checking null value

In [33]:
df.loc[df['Offer price'].notnull(), 'Offer price']

0        9499
1        6999
2        6999
3       13999
4        9499
        ...
1362     4499
1363     3999
1364     1099
1365     1299
1366     1199
Name: Offer price, Length: 1105, dtype: object

- null value check krke data type update krna

In [34]:
df.loc[df['Offer price'].notnull(), 'Offer price']=df.loc[df['Offer price'].notnull(), 'Offer price'].astype(float)

In [35]:
df.head()

,Smartphone,Rating,Reviews count,Offer price,Actual price,Saving,Delivery,Status of stock & more offers
0,"Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage) | 2....",4.2,87809,9499.0,"₹10,999","Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN
1,"Redmi 9A (Nature Green, 2GB RAM, 32GB Storage)...",4.2,74587,6999.0,"₹8,499","Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
2,Redmi 9A (Sea Blue 2GB RAM 32GB Storage) | 2GH...,4.2,74587,6999.0,"₹8,499","Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
3,"Redmi Note 10 (Aqua Green, 4GB RAM, 64GB Stora...",4.2,95519,13999.0,"₹15,999","Save ₹2,000 (13%)",FREE Delivery by Amazon,NaN
4,"Redmi 9 (Carbon Black, 4GB RAM, 64GB Storage) ...",4.2,87809,9499.0,"₹10,999","Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN

In [36]:
df.dtypes

Smartphone                        object
Rating                           float64
Reviews count                      int64
Offer price                       object
Actual price                      object
Saving                            object
Delivery                          object
Status of stock & more offers     object
dtype: object

abhi bhi offer price ka data type change nhi hua qki isme null value hai ab isko 'Fillna Method' se remove krege.

# Fillna Method
(by this method all null values replaced by median)

In [37]:
df['Offer price']=df['Offer price'].fillna(df['Offer price'].median())

In [38]:
df.dtypes

Smartphone                        object
Rating                           float64
Reviews count                      int64
Offer price                      float64
Actual price                      object
Saving                            object
Delivery                          object
Status of stock & more offers     object
dtype: object

ab datatype change ho gya.

# Clean Actual Price Column

In [39]:
df['Actual price']= df['Actual price'].str.replace('₹','')
df['Actual price']= df['Actual price'].str.replace(',','')

its remove special character

In [40]:
df.loc[df['Actual price'].notnull(), 'Actual price']=df.loc[df['Actual price'].notnull(), 'Actual price'].astype(float)

it change data type

In [41]:
df.head()

,Smartphone,Rating,Reviews count,Offer price,Actual price,Saving,Delivery,Status of stock & more offers
0,"Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage) | 2....",4.2,87809,9499.0,10999.0,"Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN
1,"Redmi 9A (Nature Green, 2GB RAM, 32GB Storage)...",4.2,74587,6999.0,8499.0,"Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
2,Redmi 9A (Sea Blue 2GB RAM 32GB Storage) | 2GH...,4.2,74587,6999.0,8499.0,"Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
3,"Redmi Note 10 (Aqua Green, 4GB RAM, 64GB Stora...",4.2,95519,13999.0,15999.0,"Save ₹2,000 (13%)",FREE Delivery by Amazon,NaN
4,"Redmi 9 (Carbon Black, 4GB RAM, 64GB Storage) ...",4.2,87809,9499.0,10999.0,"Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1311 entries, 0 to 1366
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Smartphone                     1311 non-null   object
 1   Rating                         1311 non-null   float64
 2   Reviews count                  1311 non-null   int64
 3   Offer price                    1311 non-null   float64
 4   Actual price                   998 non-null    object
 5   Saving                         1102 non-null   object
 6   Delivery                       1311 non-null   object
 7   Status of stock & more offers  473 non-null    object
dtypes: float64(2), int64(1), object(5)
memory usage: 92.2+ KB

isme null value ke karan actual price ka data type nhi change hua hai ab again fillna method use krege null value remove krne ke liye

In [43]:
df['Actual price']=df['Actual price'].fillna(df['Actual price'].median())

In [44]:
df.head()

,Smartphone,Rating,Reviews count,Offer price,Actual price,Saving,Delivery,Status of stock & more offers
0,"Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage) | 2....",4.2,87809,9499.0,10999.0,"Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN
1,"Redmi 9A (Nature Green, 2GB RAM, 32GB Storage)...",4.2,74587,6999.0,8499.0,"Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
2,Redmi 9A (Sea Blue 2GB RAM 32GB Storage) | 2GH...,4.2,74587,6999.0,8499.0,"Save ₹1,500 (18%)",FREE Delivery by Amazon,NaN
3,"Redmi Note 10 (Aqua Green, 4GB RAM, 64GB Stora...",4.2,95519,13999.0,15999.0,"Save ₹2,000 (13%)",FREE Delivery by Amazon,NaN
4,"Redmi 9 (Carbon Black, 4GB RAM, 64GB Storage) ...",4.2,87809,9499.0,10999.0,"Save ₹1,500 (14%)",FREE Delivery by Amazon,NaN

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1311 entries, 0 to 1366
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Smartphone                     1311 non-null   object
 1   Rating                         1311 non-null   float64
 2   Reviews count                  1311 non-null   int64
 3   Offer price                    1311 non-null   float64
 4   Actual price                   1311 non-null   float64
 5   Saving                         1102 non-null   object
 6   Delivery                       1311 non-null   object
 7   Status of stock & more offers  473 non-null    object
dtypes: float64(3), int64(1), object(4)
memory usage: 92.2+ KB

# Clean Saving Column

In [46]:
df['Saving'].str.split(' ')

0       [Save, ₹1,500, (14%)]
1       [Save, ₹1,500, (18%)]
2       [Save, ₹1,500, (18%)]
3       [Save, ₹2,000, (13%)]
4       [Save, ₹1,500, (14%)]
                ...
1362    [Save, ₹1,500, (25%)]
1363    [Save, ₹1,000, (20%)]
1364      [Save, ₹600, (35%)]
1365      [Save, ₹400, (24%)]
1366    [Save, ₹1,300, (52%)]
Name: Saving, Length: 1311, dtype: object

In [47]:
df['Saving'].str.split(' ').str.get(1)

0       ₹1,500
1       ₹1,500
2       ₹1,500
3       ₹2,000
4       ₹1,500
         ...
1362    ₹1,500
1363    ₹1,000
1364      ₹600
1365      ₹400
1366    ₹1,300
Name: Saving, Length: 1311, dtype: object

In [48]:
df['Saving']=df['Saving'].str.split(' ').str.get(1)

get(1) this is use for index

In [49]:
df['Saving'].unique()

array(['₹1,500', '₹2,000', '₹2,500', 'it', nan, '₹5,000', '₹50', '₹3,000',
       '₹700', '₹3,500', 'Delivery', '₹6,000', '₹500', '₹4,000', '₹675',
       '₹1,000', '₹172', '₹8,000', '₹85', '₹209', '₹247', '₹91', '₹273',
       '₹158', '₹295', '₹1,700', '₹175', '₹3,901', '₹393', '₹274', '₹90',
       '₹4,500', '₹4,999', '₹250', '₹188', '₹4,901', '₹280', '₹2,901',
       '₹63', '₹169', '₹109', '₹316', '₹3,551', '₹24,000', '₹6,529',
       '₹26,001', '₹249', '₹508', '₹5,004', '₹1,208', '₹30,000',
       '₹14,000', '₹13,000', '₹943', '₹5,499', '₹30,200', '₹170',
       '₹1,550', '₹1,109', '₹2,090', '₹13,009', '₹5,306', '₹200',
       '₹5,950', '₹14', '₹5,169', '₹8,245', '₹164', '₹550', '₹1,999',
       '₹4,300', '₹1,096', '₹5,148', '₹351', '₹1,509', '₹362', '₹58',
       '₹6,401', '₹4,509', '₹7,000', '₹100', '₹40', '₹1,149', '₹2,009',
       '₹7,053', '₹2,490', '₹28,908.36', '₹223', '₹11,000', '₹1,058',
       '₹29,520', '₹3,054', '₹2,114', '₹217', '₹499.10', '₹3,910',
       '₹1,009', '₹150', '₹1,319', '₹220', '₹10,000', '₹800', '₹650',
       '₹20,949', '₹1', '₹5,181', '₹2,149', '₹146', '₹499', '₹901',
       '₹900', '₹350', '₹56,301', '₹13,100', '₹300', '₹5,601', '₹3,009',
       '₹449', '₹3,799', '₹99', '₹1,600', '₹160', '₹809', '₹1,991',
       '₹30,659', '₹24,901', '₹4,199', '₹3,509', '₹6,491', '₹3,991',
       '₹991', '₹6,150', '₹10,249', '₹26,190', '₹17,910', '₹2,300',
       '₹1,997', '₹213', '₹27,010', '₹9,210', '₹1,019', '₹7,269',
       '₹10,100', '₹7,910', '₹39,001', '₹174', '₹912', '₹491', '₹1,025',
       '₹6,580', '₹8,090', '₹510', '₹440', '₹1,551', '₹10,609', '₹39,969',
       '₹5,160', '₹8,400', '₹600', '₹1,300', '₹1,499', '₹2,991', '₹2,077',
       '₹237', '₹21,010', '₹11,100', '₹3,165', '₹12,000', '₹21,440',
       '₹2,501', '₹309', '₹2,168', '₹850', '₹5,590', '₹20,000', '₹1,491',
       '₹756', '₹441', '₹422.75', '₹1,474', '₹2,095', '₹34,010', '₹8,100',
       '₹6,050', '₹801', '₹5,600', '₹1,209', '₹3,140', '₹151', '₹29,100',
       '₹474', '₹12,990', '₹17,610', '₹14,950', '₹999', '₹7,500', '₹190',
       '₹12,084', '₹10,005', '₹4,304', '₹335', '₹155', '₹12,749',
       '₹11,330', '₹379', '₹400', '₹3,200', '₹6,009', '₹25,851', '₹810',
       '₹159', '₹4,009', '₹1,950', '₹1,875', '₹16,910', '₹14,991',
       '₹11,991', '₹6,059', '₹10,010', '₹2,779', '₹12,991', '₹64',
       '₹13,010', '₹8,048', '₹720', '₹299', '₹9,200', '₹8,790', '₹4,100',
       '₹25,001', '₹1,100', '₹12,510', '₹14,010', '₹3,701', '₹454', '₹20',
       '₹17,001', '₹7,009', '₹17,750', '₹4,019', '₹9,991', '₹30,549',
       '₹2,499', '₹2,450', '₹6,069', '₹11,990', '₹101', '₹14,100', '₹450',
       '₹7,503', '₹3,020', '₹610', '₹6,610', '₹45', '₹1,864', '₹549',
       '₹1,050', '₹5,093', '₹5,250', '₹12,190', '₹422', '₹1,195',
       '₹5,050', '₹15,090', '₹566', '₹1,150', '₹5,701', '₹1,090',
       '₹13,910', '₹13,490', '₹3,110', '₹1,140', '₹649', '₹203', '₹70',
       '₹12,009', '₹130', '₹659', '₹152', '₹2,600', '₹490', '₹1,630',
       '₹18,310', '₹8,500', '₹26,530', '₹236', '₹9,000', '₹28,811',
       '₹22,010', '₹509', '₹4,800', '₹6,250', '₹4,400', '₹3,700', '₹503',
       '₹3,470', '₹749', '₹11,910', '₹3,210', '₹5,500', '₹229', '₹1,602',
       '₹1,850', '₹12,310', '₹24,001', '₹10,591', '₹199', '₹1,400',
       '₹349', '₹1,064', '₹9,860', '₹1,004', '₹724', '₹1,200', '₹3,019',
       '₹2,510', '₹2,700', '₹560', '₹1,334', '₹34', '₹240', '₹14,910',
       '₹1,800', '₹3,600', '₹1,704', '₹630', '₹15,000', '₹1,240',
       '₹1,049', '₹3,300', '₹2,331', '₹210', '₹791', '₹970', '₹4,490',
       '₹52,000', '₹6,991', '₹880', '₹7,991', '₹1,745', '₹709', '₹113',
       '₹2,200', '₹2,010', '₹62,000', '₹22', '₹9,511', '₹1,524', '₹820',
       '₹49', '₹721', '₹1,880', '₹2,430', '₹1,484', '₹2,100', '₹814',
       '₹3,597.50', '₹139', '₹1,547'], dtype=object)

In [50]:
df['Saving']= df['Saving'].str.replace('₹','')
df['Saving']= df['Saving'].str.replace(',','')
df['Saving']= df['Saving'].replace(['it','Delivery'],np.nan)

iss column me 3type ke objects hai issliye

In [51]:
df.loc[df['Saving'].notnull(), 'Saving']=df.loc[df['Saving'].notnull(), 'Saving'].astype(float)

In [52]:
df.head()

,Smartphone,Rating,Reviews count,Offer price,Actual price,Saving,Delivery,Status of stock & more offers
0,"Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage) | 2....",4.2,87809,9499.0,10999.0,1500.0,FREE Delivery by Amazon,NaN
1,"Redmi 9A (Nature Green, 2GB RAM, 32GB Storage)...",4.2,74587,6999.0,8499.0,1500.0,FREE Delivery by Amazon,NaN
2,Redmi 9A (Sea Blue 2GB RAM 32GB Storage) | 2GH...,4.2,74587,6999.0,8499.0,1500.0,FREE Delivery by Amazon,NaN
3,"Redmi Note 10 (Aqua Green, 4GB RAM, 64GB Stora...",4.2,95519,13999.0,15999.0,2000.0,FREE Delivery by Amazon,NaN
4,"Redmi 9 (Carbon Black, 4GB RAM, 64GB Storage) ...",4.2,87809,9499.0,10999.0,1500.0,FREE Delivery by Amazon,NaN

In [53]:
df.dtypes

Smartphone                        object
Rating                           float64
Reviews count                      int64
Offer price                      float64
Actual price                     float64
Saving                            object
Delivery                          object
Status of stock & more offers     object
dtype: object

In [54]:
df['Saving']=df['Saving'].fillna(df['Saving'].median())

isse null value remove ho jata uske bad

In [55]:
df.dtypes

Smartphone                        object
Rating                           float64
Reviews count                      int64
Offer price                      float64
Actual price                     float64
Saving                           float64
Delivery                          object
Status of stock & more offers     object
dtype: object

# Handling the Categorical Columns

In [56]:
df['Delivery'].value_counts()

Delivery
Paid                         652
FREE Delivery by Amazon      584
First Order Free Delivery     75
Name: count, dtype: int64

# One Hot Encoding

In [57]:
dfc = df.copy()

In [58]:
pd.get_dummies(df['Delivery'])

      FREE Delivery by Amazon  First Order Free Delivery   Paid
0                        True                      False  False
1                        True                      False  False
2                        True                      False  False
3                        True                      False  False
4                        True                      False  False
...                       ...                        ...    ...
1362                     True                      False  False
1363                     True                      False  False
1364                     True                      False  False
1365                     True                      False  False
1366                     True                      False  False

[1311 rows x 3 columns]

# Handling Null values

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1311 entries, 0 to 1366
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Smartphone                     1311 non-null   object
 1   Rating                         1311 non-null   float64
 2   Reviews count                  1311 non-null   int64
 3   Offer price                    1311 non-null   float64
 4   Actual price                   1311 non-null   float64
 5   Saving                         1311 non-null   float64
 6   Delivery                       1311 non-null   object
 7   Status of stock & more offers  473 non-null    object
dtypes: float64(4), int64(1), object(3)
memory usage: 92.2+ KB

In [60]:
(df.isnull().sum()/df.shape[0])*100

Smartphone                        0.000000
Rating                            0.000000
Reviews count                     0.000000
Offer price                       0.000000
Actual price                      0.000000
Saving                            0.000000
Delivery                          0.000000
Status of stock & more offers    63.920671
dtype: float64

# Dropping features having more than 50% null values

In [61]:
df.drop(['Status of stock & more offers'],axis=1, inplace=True)

jitne bhi column ka krna hota wo bhi comma lgakar add kr skte hai

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1311 entries, 0 to 1366
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Smartphone     1311 non-null   object
 1   Rating         1311 non-null   float64
 2   Reviews count  1311 non-null   int64
 3   Offer price    1311 non-null   float64
 4   Actual price   1311 non-null   float64
 5   Saving         1311 non-null   float64
 6   Delivery       1311 non-null   object
dtypes: float64(4), int64(1), object(2)
memory usage: 81.9+ KB

# Fillna Method

In [63]:
df['Offer price']=df['Offer price'].fillna(df['Offer price'].median())
df['Actual price']=df['Actual price'].fillna(df['Actual price'].median())

In [64]:
df.head()

,Smartphone,Rating,Reviews count,Offer price,Actual price,Saving,Delivery
0,"Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage) | 2....",4.2,87809,9499.0,10999.0,1500.0,FREE Delivery by Amazon
1,"Redmi 9A (Nature Green, 2GB RAM, 32GB Storage)...",4.2,74587,6999.0,8499.0,1500.0,FREE Delivery by Amazon
2,Redmi 9A (Sea Blue 2GB RAM 32GB Storage) | 2GH...,4.2,74587,6999.0,8499.0,1500.0,FREE Delivery by Amazon
3,"Redmi Note 10 (Aqua Green, 4GB RAM, 64GB Stora...",4.2,95519,13999.0,15999.0,2000.0,FREE Delivery by Amazon
4,"Redmi 9 (Carbon Black, 4GB RAM, 64GB Storage) ...",4.2,87809,9499.0,10999.0,1500.0,FREE Delivery by Amazon

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1311 entries, 0 to 1366
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Smartphone     1311 non-null   object
 1   Rating         1311 non-null   float64
 2   Reviews count  1311 non-null   int64
 3   Offer price    1311 non-null   float64
 4   Actual price   1311 non-null   float64
 5   Saving         1311 non-null   float64
 6   Delivery       1311 non-null   object
dtypes: float64(4), int64(1), object(2)
memory usage: 81.9+ KB